#!/bin/sh
#SBATCH --job-name=md
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --partition=3080ti

echo "SLURM_SUBMIT_DIR is $SLURM_SUBMIT_DIR"

echo "Starting job $SLURM_JOB_ID at " `date`

echo "Running on nodes: $SLURM_NODELIST"

start=$(date +%s)
source /share/app/anaconda3/envs/SevenNet/env.sh

python sevennet_md.py

end=$(date +%s)
take=$(( end - start ))

echo Time taken to execute commands is ${take} seconds
